image: "node:latest"

stages:
  - build
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules
    - functions/node_modules

pre:
  script:
    - rm -rf "%CACHE_PATH%/%CI_PIPELINE_ID%"
    - npm install
    - cd functions
    - npm install
    - cd ..
  stage: .pre
  artifacts:
    paths:
      - node_modules
      - functions/node_modules

build:
  script:
    - npm run build
  stage: build
  only:
    - master
  artifacts:
    paths:
      - build


deploy:
  script:
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
  stage: deploy
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
  environment:
    name: production
    url: $FIREBASE_URL
  dependencies:
    - build