image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

<<<<<<< HEAD
deploy_production:
=======
stages:
  - cd_functions
  - functions_install
  - install
  - build
  - deploy

cd_functions:
  stage: cd_functions
  only:
    - master
  script:
    - cd functions

functions_install:
  stage: functions_install
  only:
    - master
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

install:
  stage: install
  only:
    - master
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  only:
    - master
  script:
    - yarn run build
  dependencies:
    - install
  artifacts:
    paths:
      - build

deploy:
>>>>>>> master
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY