image: "node:latest"

stages:
  - build
  - deploy

cache:
  key: node_modules
  paths:
    - node_modules
    - functions/node_modules

pre:
  script:
    - npm install
    - npm install -g firebase-tools
    - cd functions
    - npm install
    - cd ..
  stage: .pre

build:
  script:
    - npm run build
  stage: build
  only:
    - master

deploy:
  script:
    - npm run deploy
  stage: deploy
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
  environment:
    name: production
    url: $FIREBASE_URL
  dependencies:
    - build