image: "node:latest"

cache:
  key: node_modules
  paths:
    - node_modules
    - functions/node_modules

stages:
  - build
  - deploy

pre:
  stage: .pre
  script:
    - npm install
    - npm install -g firebase-tools
    - cd functions
    - npm install
    - cd ..
  artifacts:
    paths:
      - node_modules/
      - functions/node_modules

build:
  stage: build
  only:
    - master
  script:
    - npm run build
  cache:
    policy: pull
    paths:
      - node_modules/
      - functions/node_modules/
  artifacts:
    paths:
      - node_modules/
      - functions/node_modules

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: $FIREBASE_URL
  only:
    - master
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - node_modules/
      - functions/node_modules/
  script:
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
